version: '3.8'
services:
  gateway:
    build: ./gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - TZ=Europe/Moscow

  server:
    build: ./server
    container_name: shareit-server
    ports:
      - "9090:9090"
      - "8082:8082"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - DB_NAME=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - TZ=Europe/Moscow

  db:
    image: postgres:13.7-alpine
    container_name: shareit-database
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - TZ=Europe/Moscow
